### PR TITLE
Synching up my origin with most recent code

### PR DESCRIPTION
**Pull request by Alex-NRCan**
Simplified the Chart type usage.
Started work on the WCAG legend instead of using the canvas.
Created a GeoChartAction principle to handle the redrawing from inside the component (instead of bothering with setTimeout from the caller).

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8)* status: 7 of 9 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan)

___
*[`src/chart.tsx` line 212 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-Ngyrrk2A1eZY08MNIfX:-Ngyrrk2A1eZY08MNIfY:b6jj9lg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart.tsx#L212)):*
> ```XML
>             else if (ds.backgroundColor) color = ds.backgroundColor! as string;
> 
>             // Return the Legent item
> ```

Typo Legent
___
*[`src/chart.tsx` line 244 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyryNP2wZAPS0q5e2x:-NgyryNP2wZAPS0q5e2y:b-tdub0k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart.tsx#L244)):*
> ```XML
>       return (
>         <div style={style} className={styles.chartContainer}>
>           <div className={styles.chartContainerGrid1}>{renderDatasetSelector()}</div>
> ```

Instead of css, can you use the MUI grid system?

We should use sxClasses and Box element to follow MUI?
___
*[`src/chart-validator.ts` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyrMxL3Q0EuQCizhiw:-NgyrMxL3Q0EuQCizhix:bz3r4g6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L41)):*
> ```XML
>                   type: 'array',
>                   items: {
>                     type: 'integer',
> ```

Should it be number?
___
*[`src/chart-validator.ts` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyrQHeBO4LPVS5r8XD:-NgyrQHeBO4LPVS5r8XE:bz3r4g6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L50)):*
> ```XML
>                     properties: {
>                       x: {
>                         type: 'integer',
> ```

Should it be number?
___
*[`src/chart-validator.ts` line 53 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyrQv9DW9MvRb4eof4:-NgyrQv9DW9MvRb4eof5:bz3r4g6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L53)):*
> ```XML
>                       },
>                       y: {
>                         type: 'integer',
> ```

Should it be number?
___
*[`src/chart-validator.ts` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-Ngyqab87IpWsP5yq2Z2:-Ngyqab87IpWsP5yq2Z3:b-t9ylz3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L68)):*
> ```XML
>                 {
>                   type: 'string',
>                   // pattern:
> ```

Can you put a description tag to put the info: Accept hexadecimal and rgba (i.e. ff000000 or rgba(255,55,255,1) instead of the whole pattern. At the end, this file may be use to genarate form for user to fill and will use description tag. It will be easier for user to understand.
___
*[`src/chart-validator.ts` line 129 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyrDGM0jWB95FTFjyn:-NgyrDGM0jWB95FTFjyo:b1ugxm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L129)):*
> ```XML
>           chart: {
>             type: 'string',
>             pattern: '^(line|bar|pie|doughnut)$',
> ```

Put an enum instead of string

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8)* status: 6 of 10 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`src/chart.tsx` line 212 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-Ngyrrk2A1eZY08MNIfX:-Ngz6ph_DSF07El51fZv:b32w1t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart.tsx#L212)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo Legent
</blockquote></details>

Ok
___
*[`src/chart.tsx` line 244 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyryNP2wZAPS0q5e2x:-NgzBdf69vvaFoZkANJT:b32w1t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart.tsx#L244)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Instead of css, can you use the MUI grid system?

We should use sxClasses and Box element to follow MUI?
</blockquote></details>

Ok
___
*[`src/chart-validator.ts` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyrMxL3Q0EuQCizhiw:-Ngz79Go0wew8y3Cl_ji:b32w1t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L41)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be number?
</blockquote></details>

Ok
___
*[`src/chart-validator.ts` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyrQHeBO4LPVS5r8XD:-Ngz78bK96QXkwq8KUyt:b32w1t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L50)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be number?
</blockquote></details>

Ok
___
*[`src/chart-validator.ts` line 53 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyrQv9DW9MvRb4eof4:-Ngz781X96BBiDfCNCon:b32w1t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L53)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be number?
</blockquote></details>

Ok
___
*[`src/chart-validator.ts` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-Ngyqab87IpWsP5yq2Z2:-Ngz7E935Z_6Dp5RE_WH:boqrxvv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L68)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put a description tag to put the info: Accept hexadecimal and rgba (i.e. ff000000 or rgba(255,55,255,1) instead of the whole pattern. At the end, this file may be use to genarate form for user to fill and will use description tag. It will be easier for user to understand.
</blockquote></details>

Yeah.. actually.. I ended up getting rid of the pattern (and left it there in case), because I *also* wanted to support color names like: 'red', 'blue' (which are indeed supported) and so I didn't want to create a whole dictionary of colors via a regex(!). So I've let it there like this for now.. I could remove the comment altogether I guess?
___
*[`src/chart-validator.ts` line 129 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyrDGM0jWB95FTFjyn:-Ngz7tI89IgtX-9phHqb:b-orumjy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L129)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put an enum instead of string
</blockquote></details>

Good point

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan)

___
*[`src/chart-validator.ts` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-Ngyqab87IpWsP5yq2Z2:-NgzHr04CWVAJi08aTWS:b-mvzohh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L68)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Yeah.. actually.. I ended up getting rid of the pattern (and left it there in case), because I *also* wanted to support color names like: 'red', 'blue' (which are indeed supported) and so I didn't want to create a whole dictionary of colors via a regex(!). So I've let it there like this for now.. I could remove the comment altogether I guess?
</blockquote></details>

I think you can remove. If you add the description tag it will explain what it support. From the string, try to create the color and if it fails, throw an error. If the input is wrong, throw error
___
*[`src/chart-validator.ts` line 129 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyrDGM0jWB95FTFjyn:-NgzHdHZ0GheO2HU6rYs:blq8ss3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L129)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Good point
</blockquote></details>

Type must be enum and put your default to line as it is the default in the code.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan)

___
*[`src/chart.tsx` line 236 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgzK_oH485Ie5czWK0x:-NgzK_oIDL29b5bo04gf:bhrds9q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/e229df1d694cfa05ba62f414132c78831c507564/src/chart.tsx#L236)):*
> ```XML
>                   defaultChecked
>                 />
>                 <Typography style={{ color: color as string }} sx={sxClasses.checkDataset} noWrap>
> ```

You can style directly in the sx like sx'{[sxClasses.check, { color: color]}}
___
*[`src/chart-validator.ts` line 129 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyrDGM0jWB95FTFjyn:-NgzL9v826vMJHrjyNL2:btbp645) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L129)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Type must be enum and put your default to line as it is the default in the code.
</blockquote></details>

"chart": {
          "enum": ["line", "bar", ...],
          "default": "line",
          "description": "Supported type of chart."

        }

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`src/chart.tsx` line 236 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgzK_oH485Ie5czWK0x:-NgzPF_v7WpyMoobsjmh:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/e229df1d694cfa05ba62f414132c78831c507564/src/chart.tsx#L236)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You can style directly in the sx like sx'{[sxClasses.check, { color: color]}}
</blockquote></details>

Done.
___
*[`src/chart-validator.ts` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-Ngyqab87IpWsP5yq2Z2:-NgzJmtREScQ8dVi3vxN:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L68)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think you can remove. If you add the description tag it will explain what it support. From the string, try to create the color and if it fails, throw an error. If the input is wrong, throw error
</blockquote></details>

Done.
___
*[`src/chart-validator.ts` line 129 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8#-NgyrDGM0jWB95FTFjyn:-NgzK2Xg63vwENypXjIj:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/3117b3ca6ca92350aa81a54632de84d181868fc8/src/chart-validator.ts#L129)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Type must be enum and put your default to line as it is the default in the code.
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
