### PR TITLE
ESLinting support and some more options in template

### PR DESCRIPTION
**Pull request by Alex-NRCan**
Now properly supporting ESLint and Prettier cloning configurations from geoview-core

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 13 of 15 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

___
*[`.eslintrc` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4#-Ngxl3Ee3ieV3HiiixV-:-Ngxl3Ee3ieV3HiiixV0:bvc7jah) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/182fb77b0257feedb5416c12c6e7a2053b848dc3/.eslintrc#L79)):*
> ```
>     }
>   }
>   
> ```

Remove trailing whitespaces
___
*[`src/chart.tsx` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4#-Ngxq2Bc0gfxyPk14f7R:-Ngxq2Bc0gfxyPk14f7S:bwtklu2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/182fb77b0257feedb5416c12c6e7a2053b848dc3/src/chart.tsx#L15)):*
> ```XML
>  */
> export interface TypeChartChartProps<TType extends GeoChartType> {
>   style?: unknown;
> ```

Better then any but still not the best.  Can we reuse style type we have in Geoview?
___
*[`src/chart-validator.ts` line 28 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4#-NgxqxM46QrhWQEn975s:-NgxqxM46QrhWQEn975t:b-6ysmdh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/182fb77b0257feedb5416c12c6e7a2053b848dc3/src/chart-validator.ts#L28)):*
> ```XML
>   };
> 
>   public SCHEMA_OPTIONS = {
> ```

In later PR this should be bring outside in a json file just for the thing we support. Let say we do not expose legend because it is always false, we can only deal with it from inside.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`src/chart.tsx` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4#-Ngxq2Bc0gfxyPk14f7R:-NgxyhSv8O7ilsur9WCy:b-i84c06) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/182fb77b0257feedb5416c12c6e7a2053b848dc3/src/chart.tsx#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Better then any but still not the best.  Can we reuse style type we have in Geoview?
</blockquote></details>

Right. I wanted to type it as `CSSProperties originally`, but that type comes from `cgpv` which is loaded later in the JSX.Element. The style is casted there. Is there another solution?
___
*[`src/chart-validator.ts` line 28 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4#-NgxqxM46QrhWQEn975s:-Ngxz0wj1fBPmqwk5a1j:b3x05dg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/182fb77b0257feedb5416c12c6e7a2053b848dc3/src/chart-validator.ts#L28)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

In later PR this should be bring outside in a json file just for the thing we support. Let say we do not expose legend because it is always false, we can only deal with it from inside.
</blockquote></details>

Will do and add an issue.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4#-:-Ngy0gc9CqnmxRiSJOrl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/4)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Pull request merged**
