### PR TITLE
Added the steps native examples

### LINKED ISSUE #6: Work on the schema validator. Think of the default params in Chart.
This issue is to remind work on the schema validator for "data" and "options" and also talk about the default params in Chart.

### PR DESCRIPTION
**Pull request by Alex-NRCan**
Added the chart line steps native examples
Made chart-validator more generic with a schema-validator
Suggestion to enforcing return types via ESLint
Moved the schema validators into json files instead of in the code

Fixes #6  and  #7 

Link to try it here: https://alex-nrcan.github.io/geochart/

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37)* status: 7 of 9 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan)

___
*[`src/app.tsx` line 44 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD12CnAOMVkW3JDLro:-NhD12CnAOMVkW3JDLrp:b-8wvrrl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/app.tsx#L44)):*
> ```XML
> 
>     // Show the error (actually, can't because the snackbar is linked to a map at the moment
>     // and geochart is standalone without a cgpv.init() at all)
> ```

Snackbar is in ui, you can't use it without a map?
___
*[`src/chart.tsx` line 241 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD1Bkx9BMi5DySWF3B:-NhD1Bkx9BMi5DySWF3C:b-xw02v5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/chart.tsx#L241)):*
> ```XML
>    */
>   const renderChartContainerFailed = (): JSX.Element => {
>     return <div style={{ fontStyle: 'italic', color: 'red' }}>Error rendering the Chart. Check console for details.</div>;
> ```

In tsx component it is better to use the mui component (Box in this case) and sx classes
___
*[`src/schema-validator.ts` line 66 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD1UsqA5mY93QL0mBc:-NhD1Usr-oZ3CevUDrQ5:btt00f1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/schema-validator.ts#L66)):*
> ```XML
>   /**
>    * Returns a string representation of the errors of all ValidatorResult objects.
>    */
> ```

Mostly for public function, can we add JSDOC @param and @return values
___
*[`src/schema-validator-data.json` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD1mqA6KD1BG126lHm:-NhD1mqA6KD1BG126lHn:b-vzrc6n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/schema-validator-data.json#L6)):*
> ```JSON
>   "description": "This Schema validator validates the GeoChart data.",
>   "type": "object",
>   
> ```

Remove trailing white spaces
___
*[`src/schema-validator-data.json` line 9 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD1q888djNl7RH4P0y:-NhD1q888djNl7RH4P0z:blmnegw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/schema-validator-data.json#L9)):*
> ```JSON
>   "properties": {
>     "labels": {
>       "description": "The labels to use for the X axis.",
> ```

Should we have labels: { x: 'my x', y: 'my y' }. It is more clear for use to fill instead of array. This can be optional and only use for bar and line chart
___
*[`src/schema-validator-data.json` line 25 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD2FDYE4GNR833XlZF:-NhD2FDYE4GNR833XlZG:bx0wta5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/schema-validator-data.json#L25)):*
> ```JSON
>           },
>           "data": {
>             "oneOf": [
> ```

Is the type of dataset link to the type of chart?
___
*[`src/schema-validator-data.json` line 52 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD2c0W0OEVXsSFVGUi:-NhD2c0W0OEVXsSFVGUj:beg0xsk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/schema-validator-data.json#L52)):*
> ```JSON
>             ]
>           },
>           "backgroundColor": {
> ```

Does style attribute should be in the data object and get ride of the array possibility.... one date, one style

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37)* status: 7 of 9 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan)

___
*[`src/schema-validator-data.json` line 52 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD2c0W0OEVXsSFVGUi:-NhD3xEg3gNFTZud7A7C:b-u3whof) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/schema-validator-data.json#L52)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Does style attribute should be in the data object and get ride of the array possibility.... one date, one style
</blockquote></details>

forget about this one, it is encapsulated in one datataset... so why the array of border?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37)* status: 7 of 9 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan)

___
*[`src/schema-validator-data.json` line 9 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD1q888djNl7RH4P0y:-NhD4ObVEeVsgs387sUO:bp4loyq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/schema-validator-data.json#L9)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we have labels: { x: 'my x', y: 'my y' }. It is more clear for use to fill instead of array. This can be optional and only use for bar and line chart
</blockquote></details>

If we do not have specific block of schema by type of chart, it make sense to have the array but we would need good description tag to explain

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37)* status: 5 of 9 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, @param, and @return)

___
*[`src/app.tsx` line 44 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD12CnAOMVkW3JDLro:-NhD3fvf5aLPeUMtrCrS:b1uona0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/app.tsx#L44)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Snackbar is in ui, you can't use it without a map?
</blockquote></details>

The function to show a Snackbar message is like: "cgpv.api.utilities.showError" which needs a 'mapId' as first parameter to raise an event that the Snackbar listens on, but I don't have a mapId (and I believe there's no Snackbar listening on anything, because cgpv was never initialized?).

If you're suggesting that I 'require' a Snackbar and build it for the template application, I could try that instead of calling the 'official' method to show messages of the api.
___
*[`src/chart.tsx` line 241 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD1Bkx9BMi5DySWF3B:-NhD4pL4CxJdGyRSEgTL:bbcye6s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/chart.tsx#L241)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

In tsx component it is better to use the mui component (Box in this case) and sx classes
</blockquote></details>

True. I need to lose my 'div' reflexes. I've updated the PR.
___
*[`src/schema-validator.ts` line 66 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD1UsqA5mY93QL0mBc:-NhD4y0WBqBRDcsKX5km:b-j37sjr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/schema-validator.ts#L66)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Mostly for public function, can we add JSDOC @param and @return values
</blockquote></details>

Yes. I've updated the PR.
___
*[`src/schema-validator-data.json` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD1mqA6KD1BG126lHm:-NhD51OCDVk_0q3ht5db:b-j37sjr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/schema-validator-data.json#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white spaces
</blockquote></details>

Yes. I've updated the PR.
___
*[`src/schema-validator-data.json` line 9 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD1q888djNl7RH4P0y:-NhD8GbR0dWUIc5x9OjU:b-n18e4v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/schema-validator-data.json#L9)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If we do not have specific block of schema by type of chart, it make sense to have the array but we would need good description tag to explain
</blockquote></details>

This is there, simply because it follows the Chart.js standard of being able to type 'generic' labels in an easy, optional way.
One can also specify axis labels in another, more custom, way too.
This generic "labels" property is optional and depends on what kind of chart you're dealing with indeed.
___
*[`src/schema-validator-data.json` line 25 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD2FDYE4GNR833XlZF:-NhD8u4_1M8IP48UveFc:bqnm28f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/schema-validator-data.json#L25)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is the type of dataset link to the type of chart?
</blockquote></details>

Some data will be more compatible with some types yes and will display weirdly in other charts.
We can start exploding the data various possibilities by chart types if we have to.
___
*[`src/schema-validator-data.json` line 52 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD2c0W0OEVXsSFVGUi:-NhD9Fa1C6Wtcbrmpm9E:b-fd8o3w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/schema-validator-data.json#L52)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

forget about this one, it is encapsulated in one datataset... so why the array of border?
</blockquote></details>

I'm not sure I understand your question, we can talk about it

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @param, and @return)

___
*[`src/app.tsx` line 44 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD12CnAOMVkW3JDLro:-NhRajUMAJH5kgm9hrfr:b-a4w3yw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/app.tsx#L44)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

The function to show a Snackbar message is like: "cgpv.api.utilities.showError" which needs a 'mapId' as first parameter to raise an event that the Snackbar listens on, but I don't have a mapId (and I believe there's no Snackbar listening on anything, because cgpv was never initialized?).

If you're suggesting that I 'require' a Snackbar and build it for the template application, I could try that instead of calling the 'official' method to show messages of the api.
</blockquote></details>

Ok so we have 3 choices:
- make our utilities in geoview-core be use without at map at all
- if chart is started from package, throw the error to the package and the package will start the snackbar
- Create a new mechanisim in the geochart package

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, @param, and @return)

___
*[`src/app.tsx` line 44 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-NhD12CnAOMVkW3JDLro:-NhRdRMVBrBb_frNXOxz:b5tvzu4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/5b7a2b24bfe1751caf714618f994660f52625889/src/app.tsx#L44)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Ok so we have 3 choices:
- make our utilities in geoview-core be use without at map at all
- if chart is started from package, throw the error to the package and the package will start the snackbar
- Create a new mechanisim in the geochart package
</blockquote></details>

Yes. My comment in the code suggests that we could do something like point #1.

When you say the "package", are you talking about the geoview-geochart "plugin"?
If yes, then I'm already doing point #2 if you look at the geoview-geochart plugin (and no need for #3) :)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37#-:-NhRgyuu0n-WXhuOLv-m:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/37)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
