### PR TITLE
Support for lazy loading via 'selectedDatasource', loading circle, better color palettes mngmt, support null values on y axis

### PR DESCRIPTION
**Pull request by Alex-NRCan**
Added new option for borderWidth
Added a new test case with steps
Adjusted the height and position of the Y slider a bit in the ui
New isLoading param when the chart is loading stuff
Now the GeoDatasource items can be null to allow for lazy loading
Improved loading spinner when loading the chart or loading a datasource to align even better with lazy loading
Cleaner isLoading functions
Supporting null as possible value for y axis
Supporting the ChartJS default colors
Better support for the color palettes (clearer/better to set in config and more possibilities) Reworked the sample data examples
Some simplification of typing and cleaned TODOs

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan)

___
*[`index.html` line 482 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44#-NiezKLW2fP0iBUsARwT:-NiezKLW2fP0iBUsARwU:b-vzrc6n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/741037aeee6c3c3570fe3f6f3acb5b7726d09c70/index.html#L482)):*
> ```HTML
>         }
>       };
>       
> ```

Remove trailing white spaces
___
*[`index.html` line 570 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44#-NiezQsi2pNipfUqH6e0:-NiezQsi2pNipfUqH6e1:b-vzrc6n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/741037aeee6c3c3570fe3f6f3acb5b7726d09c70/index.html#L570)):*
> ```HTML
>         }
>       };
>       
> ```

Remove trailing white spaces
___
*[`src/app.tsx` line 104 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44#-Niezpm46Y1gLwj1ihG_:-Niezpm46Y1gLwj1ihGa:bswn0v4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/741037aeee6c3c3570fe3f6f3acb5b7726d09c70/src/app.tsx#L104)):*
> ```XML
>     // a map and we're not even running a cgpv.init() at all here.
>     // eslint-disable-next-line no-alert
>     alert(`There was an error parsing the Chart inputs.\n\n${msgAll}\n\nView console for details.`);
> ```

We should trap if the chart is called vanilla or by geoview. if vanilla it throws the alert, if not it thros the error to geociew package to use the snackbar
___
*[`src/chart-types.ts` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44#-Nif2ibBAzQ761-tXyxq:-Nif2ibBAzQ761-tXyxr:bsch6tj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/741037aeee6c3c3570fe3f6f3acb5b7726d09c70/src/chart-types.ts#L103)):*
> ```XML
>   property: string;
>   usePalette?: boolean;
>   palette_backgrounds: string[];
> ```

Why attribute is x_x instead of xX
___
*[`src/chart-types.ts` line 178 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44#-Nif3-vd2pMDzA6QLuSc:-Nif3-vd2pMDzA6QLuSd:bks2zbj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/741037aeee6c3c3570fe3f6f3acb5b7726d09c70/src/chart-types.ts#L178)):*
> ```XML
>  * The alternate color palette to be used when no alternate color palette is specified, used for pie and doughnut charts
>  */
> export const DEFAULT_COLOR_PALETTE_CUSTOM_ALT_TRANSPARENT: string[] = [
> ```

Instad of ALT would we want PIE in the name so it is more explicit?
___
*[`src/chart-util.ts` line 61 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44#-Nif3As9B--rxNhlj-oH:-Nif3AsADIvQMVgYJiy3:b75409q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/741037aeee6c3c3570fe3f6f3acb5b7726d09c70/src/chart-util.ts#L61)):*
> ```XML
> 
>   // // Handle named colors (like "red")
>   // const opt = new Option();
> ```

Do we need dead code?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44)* status: all files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan)

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44)* status: all files reviewed, 6 unresolved discussions (waiting on @jolevesq)

___
*[`index.html` line 482 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44#-NiezKLW2fP0iBUsARwT:-NifBVTH3wsb5_ScyoXL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/741037aeee6c3c3570fe3f6f3acb5b7726d09c70/index.html#L482)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white spaces
</blockquote></details>

Done.
___
*[`index.html` line 570 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44#-NiezQsi2pNipfUqH6e0:-NifBVsv3tsHm_4cjKbC:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/741037aeee6c3c3570fe3f6f3acb5b7726d09c70/index.html#L570)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white spaces
</blockquote></details>

Done.
___
*[`src/app.tsx` line 104 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44#-Niezpm46Y1gLwj1ihG_:-NifBxvN9FWyRBqYYfCt:b-1ob10) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/741037aeee6c3c3570fe3f6f3acb5b7726d09c70/src/app.tsx#L104)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should trap if the chart is called vanilla or by geoview. if vanilla it throws the alert, if not it thros the error to geociew package to use the snackbar
</blockquote></details>

Since this code is in "app.tsx" not in "chart.tsx" it necessarily means it's only executed in vanilla chart. It's why I put the alert there actually :)
The error coming from "chart.tsx" is raised via onError callback:
 - in "app.tsx" it's an alert handing it
 - in "geochart.tsx plugin" it's the snackbar handling it
___
*[`src/chart-types.ts` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44#-Nif2ibBAzQ761-tXyxq:-NifCS1_4MaRQggKedZ1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/741037aeee6c3c3570fe3f6f3acb5b7726d09c70/src/chart-types.ts#L103)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why attribute is x_x instead of xX
</blockquote></details>

Done.
___
*[`src/chart-types.ts` line 178 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44#-Nif3-vd2pMDzA6QLuSc:-NifDNMg5L__Cozjjbum:b-xyc6mz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/741037aeee6c3c3570fe3f6f3acb5b7726d09c70/src/chart-types.ts#L178)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Instad of ALT would we want PIE in the name so it is more explicit?
</blockquote></details>

Hmmm, I put 'alt' as an alternate color palette which is currently used by PIE and DOUGHNUT and eventually others. Still, I can put PIE if you prefer.
___
*[`src/chart-util.ts` line 61 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44#-Nif3As9B--rxNhlj-oH:-NifDds95WDIIgwecdxw:b-trh4r8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/741037aeee6c3c3570fe3f6f3acb5b7726d09c70/src/chart-util.ts#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need dead code?
</blockquote></details>

I'll add a TODO. Will probably end up get rid of it yes, just want to see how it goes and if we really won't need it.

**Review by jolevesq — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
