### PR TITLE
add markers to x & y sliders under geochart & update font family

### PR DESCRIPTION
**Pull request by mayurmarakana89**
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/71)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/71)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @mayurmarakana89)

___
*[`src/chart-style.ts` line 58 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/71#-NshUzEhCoaou8J4f99A:-NshUzEhCoaou8J4f99B:bnxxgua) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/c386627ce6468efd2cf3e7f6f5a14651d557582b/src/chart-style.ts#L58)):*
> ```XML
>       fontFamily: theme.typography.h5.fontFamily,
>       fontWeight: theme.typography.h5.fontWeight,
>       fontSize: theme.typography.h5.fontSize,
> ```

We should use  theme.palette.geoViewFontSize.xx for font size
___
*[`src/chart-style.ts` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/71#-NshUyA02x8GYRqhLDmq:-NshUyA02x8GYRqhLDmr:bnxxgua) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/c386627ce6468efd2cf3e7f6f5a14651d557582b/src/chart-style.ts#L72)):*
> ```XML
>       fontFamily: theme.typography.body1.fontFamily,
>       fontWeight: theme.typography.fontWeightBold,
>       fontSize: theme.typography.body1.fontSize,
> ```

We should use  theme.palette.geoViewFontSize.xx for font size

**Comment by cphelefu** [comment]
*[`src/chart-style.ts` line 58 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/71#-NshUzEhCoaou8J4f99A:-NsiHV6u6iR58Vr-nPPB:b1ayded) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/c386627ce6468efd2cf3e7f6f5a14651d557582b/src/chart-style.ts#L58)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should use  theme.palette.geoViewFontSize.xx for font size
</blockquote></details>

Yes, we should. Feel free to  add more font sizes if necessary

**Review by mayurmarakana89 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/71)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`src/chart-style.ts` line 58 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/71#-NshUzEhCoaou8J4f99A:-Ntaygs56rmV00Tq8xKX:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/c386627ce6468efd2cf3e7f6f5a14651d557582b/src/chart-style.ts#L58)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Yes, we should. Feel free to  add more font sizes if necessary
</blockquote></details>

Done.
___
*[`src/chart-style.ts` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/71#-NshUyA02x8GYRqhLDmq:-NtayiIMDM2So9Gyf1n7:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geochart/blob/c386627ce6468efd2cf3e7f6f5a14651d557582b/src/chart-style.ts#L72)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should use  theme.palette.geoViewFontSize.xx for font size
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geochart/71)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
